width:  178
height: 218
channels: 3
files_location: ~/.cache/torchvision_dataset
train:
  _target_: torchvision.datasets.CelebA
  root: ${dataset.files_location}
  split: train
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
val:
  _target_: torchvision.datasets.CelebA
  root: ${dataset.files_location}
  split: valid
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
